name: Depoy webdemo
on:
    push:
        branches:
            - main
jobs:
    ghcjs:
        name: GHC Javascript Job
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: './'
        permissions:
          contents: write

        steps:
        - uses: actions/checkout@v4
        - name: Install emscripten
          uses: mymindstorm/setup-emsdk@v14
        - name: Add GHCup release channel for crosscompiler
          run: ghcup config add-release-channel https://raw.githubusercontent.com/haskell/ghcup-metadata/develop/ghcup-cross-0.0.8.yaml
        - name: Install GHC cross compiler
          run: emconfigure ghcup install ghc --set javascript-unknown-ghcjs-9.6.2
        - name: Update cabal
          run: cabal update
        - name: Build project
          run: cabal build --with-compiler=javascript-unknown-ghcjs-ghc --with-hc-pkg=javascript-unknown-ghcjs-ghc-pkg web-app
        - name: Move files
          run: |
            mkdir ../public
            mv dist-newstyle/build/javascript-ghcjs/ghc-9.6.2/one-sided-sequent-0.1/x/web-app/build/web-app/web-app.jsexe/all.js ../public
            mv web-app/index.html ../public
            mv web-app/main.css   ../public
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: ../public
            git-config-name: one-sided-sc
            git-config-email: '<>'
            repository-name: ps-tuebingen/one-sided-sc-web.io
            ssh-key: ${{ secrets.ONE_SIDED_SSH }}
            commit-message: 'Deploy webdemo'
            single-commit: true
